#Student id - 1155825, Shubham Parth

#The data set used in this assignment contains a list of countries that have capability of producing nuclear power.
#The data set contains names of these countries, the amount of electricity generated by them, number of operating 
#nuclear reactors and nuclear power output as a percentage of the total electricity output.
#3 graphical visualizations have been shown based on this data set. All these graphical visualizations complement 
#each other in showing how the nuclear power is distributed around the world.


#NOTE : The plots may appear missing when plotted on the Rstudio "Plots" section. When exported as a pdf file
#of "A4" or "US Legal-" size, the plots appear just fine.
#The plots can also be viewed by using the "Zoom" function in Plots tab of Rstudio
#The plots are automatically saved when the code runs its full course.-


#Installing the required packages
install.packages('tidyverse')
install.packages('sf')
install.packages('rvest')
install.packages('stringr')
install.packages('scales')
install.packages('ggplot2')
install.packages('cowplot')
install.packages('maps')


#------------------------------------------------------------------------------------------------------------------------------

#Importing required packages for use
library(tidyverse)
library(sf)
library(rvest)
library(stringr)
library(scales)
library(ggplot2)
library(cowplot)
library(maps)
#------------------------------------------------------------------------------------------------------------------------------

#setting working directory where the data set and files are stored
#Please change the path for the directory where data set is present
setwd('C:/Users/Skynet/Desktop/R tutorials/Assignment1/Assignment 1')

#Reading the data set .csv file
nuclear <- read.csv(file = 'Dataset nuclear - Sheet1.csv',header=TRUE)

#Modifying the data frame with first row are headers
names(nuclear) <- as.matrix(nuclear[1, ])
nuclear <- nuclear[-1, ]

#changing header names for our use
colnames(nuclear) <- c('country', 'OR', 'UC','capacity','generated','percentshare','O power','UC power','closed')

#Modifying columns to remove commas and make the data integer so that it can be used
nuclear <- nuclear %>% mutate(generated = generated %>% str_replace_all(',','') %>% as.integer())
nuclear <- nuclear %>% mutate(percentshare = percentshare %>% str_replace_all('%','') %>% as.integer())

#storing world map with coordinates in map.world data frame
map.world <- map_data('world')

#checking to see if there are any countries with different names in our data set
anti_join(nuclear, map.world, by = c('country' = 'region'))

#Printing to see the country names in world map data set
map.world %>%
  group_by(region) %>%
  summarise() %>%
  print(n = Inf)


#Changing name of countries that need to be modified in our data set 
nuclear <- nuclear %>%  mutate(country = recode(country, `United States` = 'USA'
                                                , `United Kingdom` = 'UK'
                                                , `Korea, Republic of` = 'South Korea'
                                                
)
)


#combining world map and our modified data frame
map.nuclear <- left_join( map.world, nuclear, by = c('region' = 'country')) 

#------------------------------------------------------------------------------------------------------------------------------

#creating Map for Nations based on electricity generated with all themes and scales. Breaks have been set manually to show maximum difference possible
map1 <- ggplot(map.nuclear, aes( x = long, y = lat, group = group )) +
  geom_polygon(aes(fill = generated),colour="gray") + 
  scale_fill_gradientn(colours = c('#461863','#404E88','#2A8A8C','#7FD157','#F9E53F'),values = scales::rescale(c(10000,70000,150000,380000,800000)),labels = c("0 - 10K", "10K - 100K", "100K - 200K", "200K - 400K", "400K - 800K"),breaks = c(10000,70000,150000,380000,800000))+
  guides(fill = guide_legend(reverse = T)) +
  labs(fill = 'GWh',title = 'Nations based on nuclear electricity generated, 2019',subtitle = 'Gigawatt-hours',x = NULL,y = NULL) +
  theme(text = element_text(, color = '#EEEEEE'),plot.title = element_text(size = 15),plot.subtitle = element_text(size = 14),axis.ticks = element_blank(),axis.text = element_blank(),panel.grid = element_blank(),panel.background = element_rect(fill = '#333333'),plot.background = element_rect(fill = '#333333'),legend.position = c(.18,.36),legend.background = element_blank(),legend.key = element_blank()) 


#------------------------------------------------------------------------------------------------------------------------------



#creating Map for nations based on nuclear output as a percentage of total power output. Percentage has been shown in this map based on growing shade of green color
map2 <- ggplot(map.nuclear, aes( x = long, y = lat, group = group )) +
  geom_polygon(aes(fill = percentshare),colour="gray") +
  scale_fill_gradient( low="#d2f8d2" , high = "#037f51",
  labels= paste(c("0% - 10%","10% - 20%","20% - 30%","30% - 40%","40% - 50%","60% - 70%","> 70%",80,90,100)),breaks=c(10,20,30,40,50,60,70,80,90,100))+
  guides(fill = guide_legend(reverse = T)) +
  labs(fill = 'Percent/Total power',title = 'Nations based on nuclear output as a percentage of total power output',subtitle = 'Percent of total power, 2019',x = NULL,y = NULL) +
  theme(text = element_text(color = '#EEEEEE'),plot.title = element_text(size = 15),plot.subtitle = element_text(size = 14),axis.ticks = element_blank(),axis.text = element_blank(),panel.grid = element_blank(),panel.background = element_rect(fill = '#333333'),plot.background = element_rect(fill = '#333333'),legend.position = c(.18,.36),legend.background = element_blank(),legend.key = element_blank()) 


#------------------------------------------------------------------------------------------------------------------------------

#creating a new data frame "nuclear_bar" in order to make customisations for bar graph to be made
nuclear_bar <- nuclear
nuclear_bar <- nuclear_bar %>% mutate(OR = OR %>% as.integer())
nuclear_bar <- nuclear_bar %>% mutate(UC = UC %>% as.integer())
nuclear_bar <- nuclear_bar %>% mutate(closed = closed %>% as.integer())
nuclear_bar$total <- nuclear_bar$OR + nuclear_bar$UC + nuclear_bar$closed

#reordering the data frame based on "OR" column in decreasing order
nuclear_bar[order(nuclear_bar$OR, decreasing = TRUE),]


# Storing Data of top 15 countries based on number of operating reactors in a separate data frame
Top15countries <- top_n(nuclear_bar, 15, OR)


#Creating a new data frame with values for a stacked representation of values
df2 <- rbind ( data.frame(Top15countries$country, "count" = Top15countries$UC , "type"="Reactors under construction"),
               data.frame(Top15countries$country , "count" = Top15countries$OR , "type"="Reactors Operating"),
               data.frame(Top15countries$country , "count" = Top15countries$closed , "type"="Reactors shutdown"))

#Creating a Bar plot based on the number of reactors in each country with the x axis displaying the name of countries and y axis displaying the number of reactors. Both the axis have been flipped for better representation.
#values for only operating reactors have been shown to display data that is 
bar <- ggplot(df2, aes(x= reorder(Top15countries.country,count), y=count, fill=factor(type, levels=c( "Reactors shutdown","Reactors under construction","Reactors Operating")))) +
  geom_bar(stat="identity", position= "stack") + coord_flip() + scale_y_continuous(breaks = seq(0, 150, by = 10)) + 
  labs(fill = "Reactors")+
  geom_text(data=subset(df2,type=="Reactors Operating"),aes(label = count), size = 3, hjust = 2, position ="stack")+
  ylab("Number of reactors") + xlab("Countries") + ggtitle("Nations based on number of Nuclear Reactors") +
  theme(plot.title = element_text( face = "bold", size = (11),hjust=0.5))

#------------------------------------------------------------------------------------------------------------------------------


#plotgrid has been used in order to display all the above mentioned plots at the same time.
plotgrid <- plot_grid(map1,map2,bar , ncol=1)
plotgrid

#The plots formed have been saved in a .pdf format with the given width and height in order to display them in best resolution and size. 
ggsave(filename="1155825_assignment1.pdf", plot=plotgrid , width = 8.5, height = 14, units = "in")

dev.off

